# Generated by Django 3.2.5 on 2021-07-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaxStoreid',
            fields=[
                ('max_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('url', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('encode', models.CharField(max_length=70)),
            ],
        ),
    ]
