# Generated by Django 3.2.5 on 2021-07-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urldata',
            name='id',
        ),
        migrations.AlterField(
            model_name='urldata',
            name='url',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
