# Generated by Django 3.2.5 on 2021-07-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_auto_20210730_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxStoreid',
            fields=[
                ('max_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
